### ISSUE TITLE
refresh token ?

### ISSUE THREAD

**Issue by imbibinebe** [ikkez/f3-opauth#1]
Hi ikkez,
I'd like to get a refresh token when connecting threw google for example (https://developers.google.com/identity/protocols/OpenIDConnect). Is this possible with your library ?
Best,
Tin

**Comment by ikkez** [comment]
The used library for google is the usual google strategry provided by opauth: https://github.com/opauth/google
Its implementation is based on OAuth 2.0, so maybe have a look at the linked OAuth2 references.
As far as I can see, the refresh_token should be there somewhere: https://github.com/opauth/google/blob/master/GoogleStrategy.php#L93

**Comment by imbibinebe** [comment]
Perfect. In fact I just had to add
access_type = offline
in opauth.ini
Thanks !
