### ISSUE TITLE
Please explain to a novice PHP developer how to implement this plugin.

### ISSUE THREAD

**Issue by rontornambe** [ikkez/f3-opauth#2]
I am a PHP newbie and find your plugin interesting but  the documentation a bit sparse for my level of understanding. Where does the $f3->set('AUTOLOAD','lib/opauth/'); get called from?

My index.php file (in the same folder as opauth.ini) looks like:

<?php

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);

$f3->config('opauth.ini', TRUE);

// init with config
$opauth = OpauthBridge::instance($f3->opauth);

// define login handler
$opauth->onSuccess(
    function($data){
    header('Content-Type: text');
    echo 'User successfully authenticated.'."\n";
    print_r($data['info']);
});

// define error handler
$opauth->onAbort(function($data){
    header('Content-Type: text');
    echo 'Auth request was canceled.'."\n";
    print_r($data);
});
?>

but I get the error:
The writers-tryst-test.ron-tornambe.com page isn’t working

My URL is "http://writers-tryst-test.ron-tornambe.com/opauth/index.php"

TIA
Ron

**Comment by ikkez** [comment]
No Problem. See basic fat-free sample for bootstrap index.php http://fatfreeframework.com/getting-started#Hello,World:TheLess-Than-A-MinuteFat-FreeRecipe

```php
<?php
$f3 = require('lib/base.php'); // init the framework
$f3->set('AUTOLOAD','lib/,lib/opauth/'); // add the opauth path to the autoload var
// ...
```

**Comment by rontornambe** [comment]
Thanks for the prompt reply.

I tried running the hello world example, but receive an error (HTTP 404
(GET /index.php). I am running PHP 5.5. Here's my index.php (in root
folder):

<?php$f3 = require('php/fatfree-master/lib/base.php');$f3->route('GET /',
    function() {
        echo 'Hello, world!';
    });$f3->run();

?>

What am I missing?

TIA,
Ron Tornmabe

**Comment by ikkez** [comment]
Don't put index.php in your url address. the default route is just `/`.

**Comment by rontornambe** [comment]
Got it. Thanks again.

**Comment by rontornambe** [comment]
Would you kindly show the code needed to authenticate Facebook or Google?
Here is what I have so far:

<?phprequire "php/f3-oauth/OpauthBridge.php";$f3 =
require('php/fatfree-master/lib/base.php');
 $f3->set('AUTOLOAD','php/f3-oauth/'); // add the opauth path to the
autoload $f3->config('php/f3-oauth/opauth.ini', true);$opauth =
OpauthBridge::instance($f3->opauth);
 header('Location:
http://writers-tryst.ron-tornambe.com/php/f3-oauth/Strategy/Facebook/');
 // define login handler$opauth->onSuccess(function($data){
    header('Content-Type: text');
    echo 'User successfully authenticated.'."\n";
    print_r($data['info']);});
 // define error handler$opauth->onAbort(function($data){
    header('Content-Type: text');
    echo 'Auth request was canceled.'."\n";
    print_r($data);});?>

**Comment by ikkez** [comment]
please read the [README](https://github.com/ikkez/f3-opauth/blob/master/README.md). It already contains a working demo and describes all things needed.

**Comment by rontornambe** [comment]
I have read the readme at least ten times. The Facebook demo does not work
and there is nothing that shows any code that implements authentication.

**Comment by ikkez** [comment]
To clearify things. This is a plugin that makes integration of the OPauth framework easierer for F3. It's only a configuration wrapper, all authentication implementations are made in the opauth strategies and the opauth base framework, which are included in here. In the [config file](https://github.com/ikkez/f3-opauth/blob/master/lib/opauth/opauth.ini) you'll find the keys for your specific apps you need to setup for your website.. it's possible that my app ids only work on my server/domain. So you need to create your own facebook app first. from the readme:
> You'll find instructions how to do that in each strategy folder's readme file.
i.e: https://github.com/ikkez/f3-opauth/tree/master/lib/opauth/Strategy/Facebook
You can skip 1. here, cause it's included already.
Put the app_id and app_secret into the opauth.ini config file.

All you need to do in your index.php is:

```php
$f3 = require('lib/base.php');
$f3->concat('AUTOLOAD',';lib/opauth/');
$f3->config('lib/opauth/opauth.ini', TRUE);
$opauth = OpauthBridge::instance($f3->opauth);
$opauth->onSuccess(function($data){
    header('Content-Type: text');
    echo 'User successfully authenticated.'."\n";
    print_r($data['info']);
});
$opauth->onAbort(function($data){
    header('Content-Type: text');
    echo 'Auth request was canceled.'."\n";
    print_r($data);
});
$f3->run();
```

now call `http://yourdomain.com/auth/facebook`, and the auth process starts. 
For details about the strategies, see https://github.com/opauth/opauth

**Comment by jravia** [comment]
Error 400: redirect_uri_mismatch

The redirect URI in the request, http://localhost/f3-hindi/auth/google/oauth2callback, does not match the ones authorized for the OAuth client. 

please give clear url .. readme.md not formatted good for me.

thanks

**Comment by ikkez** [comment]
the return url is simply `/auth-return` .. you actually don't need to setup this yourself. In the google console, just leave the redirect url empty,.. it's provided by the auth request itself.
