### ISSUE TITLE
Documentation incomplete

### ISSUE THREAD

**Issue by rontornambe** [ikkez/f3-opauth#4]
The READ.ME is too sketchy for anyone to successfully implement this plugin. It is missing the $f3-run() command and does not fully explain how to authenticate any strategy.  The Facebook demo is inoperative. A working example would be very helpful.

**Comment by ikkez** [comment]
Basic knowledge about the F3 framework is required for every plugin. I 	assume that you know how to load the framework, setup routes and configs and that `$f3->run()` is always the step to kickstart the routing-engine.
My demo on my server (http://f3.ikkez.de/auth/facebook) does not use any more code than provided in this repository. I just removed the app in my facebook account and tested it once more... works fine here, just try it yourself with the demo links https://github.com/ikkez/f3-opauth#demo
I haven't written the auth strategies. Please see the opauth project for more information how the OAuth2 mechanics work, if you are interested in that.
>To login, call a strategy, i.e.http://domain.com/auth/facebook.

**Comment by rontornambe** [comment]
When writing to a general audience, it is best not to assume anything.

When I click on this link. <https://github.com/ikkez/f3-opauth#demo> I
receive the following message:

App Not Setup
This app is still in development mode, and you don't have access to it.
Switch to a registered test user or ask an app admin for permissions.

**Comment by ikkez** [comment]
ah okay,.. well in that case just create your own facebook app for testing purpose and change the app id/key settings in the config file.. 
I try to be open-minded for any hints or suggestions regarding the code and the documentation. It can occur that I do not miss these or that in docs, as it seems obvious to me, but I'll take your feedback into account. It's probably easy to add those 2-3 lines to the docs... but just to compare: if you buy a playstation game, the game's manual also do not tell you how to wire up the system with your TV.
Nevertheless, I'll update the docs.
