### ISSUE TITLE
Can you give an example to work within other controller?

### ISSUE THREAD

**Issue by seraphimchan** [ikkez/f3-opauth#5]
I tried to get the data. But it not work for me.

my index
> $opauth = OpauthBridge::instance($f3->opauth);
$opauth->onSuccess('Authentication->social');

authentication.php
> function social() {
    $opauth = new OpauthBridge($this->opauth);
      $opauth->onSuccess(function($data){
      $user = new User($this->db);
      $user->getbyEmail($data['info']['email']);
    if($user->dry()) {
      echo "Not registered";
    }
     });
    }

**Comment by ikkez** [comment]
hi. Did you load the opauth config as well? 
`$f3->config('lib/opauth/opauth.ini',true);`
Also please define "_didn't work_"!

**Comment by seraphimchan** [comment]
sorry
yes i also put on my index, but just give a blank page

**Comment by seraphimchan** [comment]
sorry.
please give some example to work with controllers, i mean not the index. i'm stuck in this
on authentication.php just give a blank page

**Comment by ikkez** [comment]
I've updated the docs. https://github.com/ikkez/f3-opauth#application-flow
you need to integrate this into your existing login function. so at Authentication->social you will have a look at the $data that comes in, and use this to fetch a user record from your database - you  already have this - great. Now if registered, log the user in by creating the user SESSION, or whatever you use to track a user, and if not, create an account for the user.

**Comment by seraphimchan** [comment]
solved, thank you
